import re
import os
import datetime

MODULE_ORDER = [
    'Icons', 'Keybinds', 'Theme', 'Utils', 'Acrylic',
    'Section', 'Tab', 'Window', 'Notify', 'Dialog', 'Config',
]

SRC = os.path.join(os.path.dirname(__file__), 'src', 'Vanta')
OUT = os.path.join(os.path.dirname(__file__), 'dist', 'main.lua')


def transform(content):
    content = re.sub(r'require\(script\.Parent\.(\w+)\)', r'_require("\1")', content)
    content = re.sub(r'require\(script\.(\w+)\)', r'_require("\1")', content)
    return content


def build():
    parts = []
    parts.append("-- Vanta UI Library")
    parts.append("-- This file is auto-generated by build.py. Do not edit directly.")
    parts.append("-- Source: https://github.com/Front-Evill/Library")
    parts.append("-- Built: " + datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"))
    parts.append("")
    parts.append("local _modules = {}")
    parts.append("local function _require(name)")
    parts.append("\treturn _modules[name]")
    parts.append("end")
    parts.append("")

    for name in MODULE_ORDER:
        path = os.path.join(SRC, name + '.lua')
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        content = transform(content)
        parts.append('_modules["%s"] = (function()' % name)
        parts.append(content.rstrip())
        parts.append('end)()')
        parts.append("")

    init_path = os.path.join(SRC, 'init.lua')
    with open(init_path, 'r', encoding='utf-8') as f:
        init_content = f.read()
    init_content = transform(init_content)

    parts.append('local function _init()')
    parts.append(init_content.rstrip())
    parts.append('end')
    parts.append("")
    parts.append('return _init()')

    bundle = "\n".join(parts) + "\n"

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(bundle)

    print("Bundled", len(MODULE_ORDER) + 1, "modules into", OUT)
    print("Total lines:", len(bundle.splitlines()))


if __name__ == '__main__':
    build()
